server {
    listen 80;
    server_name api.local;
    root /var/www/public;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass laravel:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTP_HOST $host;   # ← transmet le domaine à Laravel
        fastcgi_param SERVER_NAME $host; # ← idem
        fastcgi_param SERVER_PORT 8000; 
    }
}

server {
    listen 80;
    server_name admin.local;
    root /var/www/public;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass laravel:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTP_HOST $host;   # ← transmet le domaine à Laravel
        fastcgi_param SERVER_NAME $host; # ← idem
        fastcgi_param SERVER_PORT 8000; 
    }
}